from .materiales import Materiales
from .tiposmateriales import Tiposmateriales
from .formularios import Formularios
from .ordenes import Ordenes
from .puntos import Puntos
from .punto_recoleccion import Punto_recoleccion
from .procesos import Procesos
from .informes import Informes
from .stock import Stock
from .punto_procesos import Punto_proceso
from .evaluacion import Evaluacion
from .solicitantes import Solicitantes