# Generated by Django 4.1.3 on 2024-09-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_tiposmateriales'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eco.tiposmateriales'),
            preserve_default=False,
        ),
    ]
