# Generated by Django 4.1.3 on 2024-09-27 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_formularios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='materiales',
        ),
        migrations.AddField(
            model_name='materiales',
            name='formulario',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eco.formularios'),
        ),
    ]
