# Generated by Django 4.1.3 on 2024-09-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0008_formularios_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularios',
            old_name='estado',
            new_name='abierto',
        ),
    ]
