# Generated by Django 4.1.3 on 2024-10-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0010_puntos_ordenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenes',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eco.puntos'),
        ),
    ]
