# Generated by Django 5.1.2 on 2024-11-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0012_formularios_reciclador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto_recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
