# Generated by Django 5.1.2 on 2024-11-17 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0013_punto_recoleccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='punto_recoleccion',
            name='recicladores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
