# Generated by Django 5.1.2 on 2024-11-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0014_punto_recoleccion_recicladores'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='material_recibido',
            field=models.BooleanField(default=False),
        ),
    ]
