# Generated by Django 5.1.2 on 2024-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0016_procesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
