# Generated by Django 5.1.2 on 2024-11-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0019_remove_informes_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='informe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eco.informes'),
        ),
    ]
