# Generated by Django 5.1.2 on 2024-11-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0020_formularios_informe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='procesado',
        ),
    ]
