# Generated by Django 5.1.2 on 2024-11-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0021_remove_formularios_procesado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposmateriales',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
    ]
