# Generated by Django 5.1.2 on 2024-11-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0024_rename_abierto_informes_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tipo_material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eco.tiposmateriales')),
            ],
        ),
    ]
