# Generated by Django 5.1.2 on 2024-11-26 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0025_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
