# Generated by Django 5.1.2 on 2024-11-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0017_alter_procesos_fin'),
        ('eco', '0025_stock'),
    ]

    operations = [
    ]
