# Generated by Django 5.1.2 on 2024-11-26 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0026_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='evaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eco.evaluacion'),
        ),
    ]
