# Generated by Django 5.1.2 on 2024-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0026_merge_0017_alter_procesos_fin_0025_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='estado',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('entregado', 'Entregado'), ('recibido', 'Recibido'), ('cerrado', 'Cerrado')], default='cargado', max_length=10),
        ),
    ]
