# Generated by Django 5.1.2 on 2024-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0027_procesos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesos',
            name='estado',
            field=models.CharField(choices=[('cargado', 'Cargado'), ('entregado', 'Entregado'), ('recibido', 'Recibido'), ('cerrado', 'Cerrado'), ('notificado', 'Notificado'), ('pagado', 'Pagado')], default='cargado', max_length=10),
        ),
    ]
