# Generated by Django 5.1.2 on 2024-11-26 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0028_solicitantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estado', models.CharField(max_length=1)),
                ('tipo_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eco.tiposmateriales')),
            ],
        ),
    ]
