# Generated by Django 5.1.2 on 2024-11-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0029_punto_proceso'),
        ('eco', '0029_solicitudes_red'),
    ]

    operations = [
    ]
