# Generated by Django 5.1.2 on 2024-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0030_merge_0029_punto_proceso_0029_solicitudes_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes_red',
            name='id_externo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
