# Generated by Django 5.1.2 on 2024-11-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0032_tiposmateriales_trabajado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso_solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bonita', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
